### ISSUE TITLE
Add KhatGod to Kami its on my profile

### ISSUE THREAD

**Issue by Ihackedsctrach** [KohimaNayagato/Clients#2]
https://github.com/null3054/KhatHax-EmpHack

some kids taking it as his own so could u just add the one I had made before this

**Comment by KohimaNayagato** [comment]
bet 1s lemme check it

**Comment by KohimaNayagato** [comment]
how hard is it to upload a project properly to github omfg send a compiled jar or send the normal src not a fucking rar 🤮

**Comment by Ihackedsctrach** [comment]
thats not mine xd he compiled the jars into a rar check my profile not his

**Comment by Ihackedsctrach** [comment]
https://github.com/Ihackedsctrach/khatHack

**Comment by KohimaNayagato** [comment]
Give me an hour I've got a black eye from having the shit beat out of me and I'm having a bath rn I'll check later

**Comment by Ihackedsctrach** [comment]
ight

**Comment by KohimaNayagato** [comment]
Added
